### ISSUE TITLE
[Recommend] Change license to GPL v3

### ISSUE THREAD

**Issue by karan** [dubhacks/15s#3]
MIT allows anyone to use the source here in anything without disclosing their own source code.

GPLv3 requires them to also make their own source code public. Since this isn't a library but rather a full application, it would be better for the ecosystem if it was under GPL.

**Comment by grant** [comment]
I have considered this, but don't find a good reason why GPL is better than MIT. GPL _doesn't_ require copies of the source code to be public and it is more restrictive.
